### ISSUE TITLE
The Summary Section Overlap on Low/Medium Breakpoint

### ISSUE THREAD

**Issue by Zibilyonik** [canriquez/library#3]
The project so far looks and functions very well! I have noticed only a minor issue where the Summary sections on the index page tend to overlap when the window width is reduced under a certain value; the project will look cleaner if you can resolve that 👍 

Have a nice day!

**Comment by canriquez** [comment]
Thanks for the feedback. We have now refactored the initial table and made it responsive.
best regards.
Carlos
